version: "3.6"
services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - django
  memcached:
    image: memcached:1.6.9-alpine
    container_name: memcached
    ports:
      - 11211:11211
  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - 27017:27017
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb