version: "3.6"
services:
  nginx:
    image: opentracing/nginx-opentracing
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/jaeger-nginx-config.json:/etc/jaeger-nginx-config.json
    ports:
      - 8080:80
    depends_on:
      - django
  memcached:
    image: memcached:1.6.9-alpine
    container_name: memcached
    ports:
      - 11211:11211
    entrypoint:
      - memcached
      - -m 64

  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - 27017:27017
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - memcached
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.22
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
